# версия Docker Compose
version: '3.1'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера person-gateway
  gateway:
    # имя билда
    build: gateway
    # имя образа
    image: gateway-image
    # имя контейнера
    container_name: gateway-container
    # проброс портов
    ports:
      - "8080:8080"
    # "зависит от",
    depends_on:
      - server
    # переменные окружения
    environment:
      - PERSON_SERVER_URL=http://server:9090

  # описание контейнера person-server
  server:
    # имя билда
    build: server
    # имя образа
    image: server-image
    # имя контейнера
    container_name: server-container
    # проброс портов
    ports:
      - "9090:9090"
    # "зависит от",
    depends_on:
      - db
    # переменные окружения
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/person
      - SPRING_DATASOURCE_USERNAME=person
      - SPRING_DATASOURCE_PASSWORD=person

  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:14-alpine
    # имя контейнера
    container_name: person-db
    # переменные окружения
    environment:
      - POSTGRES_PASSWORD=person
      - POSTGRES_USER=person
      - POSTGRES_DB=person